create table hw_netology.ORDERS(
id int generated by default as identity primary key,
date timestamp not null,
customer_id int,
product_name varchar not null,
amount int not null,
foreign key (customer_id) references hw_netology.CUSTOMERS(id)
);