create table hw_netology.CUSTOMERS(
id int generated by default as identity primary key,
name varchar not null,
surname varchar not null,
age int not null,
phone_number varchar not null
);

insert into hw_netology.customers (name, surname, age, phone_number)
values ('Ivan', 'Shcheglov', 36, '+79278883388');

insert into hw_netology.customers (name, surname, age, phone_number)
values ('Anna', 'Graf', 35, '+79273338833');

insert into hw_netology.customers (name, surname, age, phone_number)
values ('Arseny', 'SHCHEGLOV', 18, '+79278883838');